apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/app-network: "true"
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_PASSWORD
              value: privet123
            - name: MYSQL_ROOT_PASSWORD
              value: privet123
            - name: MYSQL_USER
              value: user_wr
          image: mysql
          name: mysqldb
          ports:
            - containerPort: 3306
          resources: {}
          tty: true
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldbvolume
            - mountPath: /docker-entrypoint-initdb.d
              name: mysql-claim1
      restartPolicy: Always
      volumes:
        - name: mysqldbvolume
          persistentVolumeClaim:
            claimName: mysqldbvolume
        - name: mysql-claim1
          persistentVolumeClaim:
            claimName: mysql-claim1
status: {}
